### ISSUE TITLE
retrace-server-worker attempts to recreate already existing symlink

### ISSUE THREAD

**Issue by mkutlak** [abrt/retrace-server#231]
```
Traceback (most recent call last):
  File "/usr/bin/retrace-server-worker", line 69, in <module>
    worker.start(kernelver=kernelver, arch=cmdline.arch)
  File "/usr/lib/python2.7/site-packages/retrace/retrace_worker.py", line 1022, in start
    self._fail()
  File "/usr/lib/python2.7/site-packages/retrace/retrace_worker.py", line 180, in _fail
    os.path.join(task._get_file_path(RetraceTask.MISC_DIR), "retrace-log"))
OSError: [Errno 17] File exists
```

https://github.com/abrt/retrace-server/blob/87f06dd7393fb9d49704b0514037b54419765249/src/retrace/retrace_worker.py#L178

**Comment by mkutlak** [comment]
suspect: https://github.com/abrt/retrace-server/commit/daea8e841a397b2ac94c218cfb9988074bc2831d
