### ISSUE TITLE
retrace-server-interact <taskid> crash fails with "NameError: name 'List' is not defined"

### ISSUE THREAD

**Issue by DaveWysochanskiRH** [abrt/retrace-server#342]
After 88bda002503a I get
~~~
$ retrace-server-interact 307540904 crash
Traceback (most recent call last):
  File "/usr/bin/retrace-server-interact", line 25, in <module>
    def print_cmdline(cmdline: List[str]):
NameError: name 'List' is not defined
~~~

**Comment by ernestask** [comment]
What version of Python do you use?

**Comment by DaveWysochanskiRH** [comment]
> What version of Python do you use?
This is RHEL8
~~~
$ python --version
Python 3.6.8
~~~

This fixes it though not sure this is desired 
~~~
index faec0c0ac441..254da9061028 100755
--- a/src/retrace-server-interact
+++ b/src/retrace-server-interact
@@ -7,6 +7,7 @@ import sys
 import time
 from pathlib import Path
 from subprocess import list2cmdline
+from typing import List
 
 from retrace.retrace import (ALLOWED_FILES,
                              STATUS_FAIL,
~~~

**Comment by DaveWysochanskiRH** [comment]
Also after the above 1-liner I get a new error 
~~~
$ retrace-server-interact 307540904 crash
If you want to execute the command manually, you can run
Traceback (most recent call last):
  File "/usr/bin/retrace-server-interact", line 167, in <module>
    print_cmdline(cmdline)
  File "/usr/bin/retrace-server-interact", line 28, in print_cmdline
    sys.stderr.write("$ %s\n\n" % list2cmdline(cmdline))
  File "/usr/lib64/python3.6/subprocess.py", line 481, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
~~~
