### ISSUE TITLE
After 8d0469bff899 dedup_vmcore Tracebacks on Pre-Python-3.8.x (RHEL8) due to non-existent Path.link_to()

### ISSUE THREAD

**Issue by DaveWysochanskiRH** [abrt/retrace-server#357]
It looks like 8d0469bff899 introduced a problem where dedup_vmcore() now fails with the following Traceback
~~~
==> /var/log/retrace-server/cleanup_error.log-20200805 <==
    total_savings += worker.dedup_vmcore(md5_tasks[md5])
  File "/usr/lib/python3.6/site-packages/retrace/retrace_worker.py", line 627, in dedup_vmcore
    v2_link.link_to(v1)
AttributeError: 'PosixPath' object has no attribute 'link_to'
Traceback (most recent call last):
  File "/usr/bin/retrace-server-cleanup", line 145, in <module>
    total_savings += worker.dedup_vmcore(md5_tasks[md5])
  File "/usr/lib/python3.6/site-packages/retrace/retrace_worker.py", line 627, in dedup_vmcore
    v2_link.link_to(v1)
AttributeError: 'PosixPath' object has no attribute 'link_to'

~~~
I think the issue is that 'link_to' was only added in Python 3.8 and RHEL8 only has Python 3.6:
[Python 3.8 link_to](https://docs.python.org/3/library/pathlib.html)

**Comment by DaveWysochanskiRH** [comment]
This patch seems to work for me, but not sure if there's something else preferred, or what the baseline Python version we're shooting for.  I'll submit a PR for it and we can discuss.
~~~
 diff -Nurp /usr/lib/python3.6/site-packages/retrace/retrace_worker.py.orig /usr/lib/python3.6/site-packages/retrace/retrace_worker.py
--- /usr/lib/python3.6/site-packages/retrace/retrace_worker.py.orig     2020-08-05 13:59:06.596024382 -0400
+++ /usr/lib/python3.6/site-packages/retrace/retrace_worker.py  2020-08-05 13:59:55.571953347 -0400
@@ -624,7 +624,7 @@ class RetraceWorker:
 
         v2_link = Path(str(v2) + "-link")
         try:
-            v2_link.link_to(v1)
+            os.link(str(v1), str(v2_link))
         except OSError:
             log_warn("Failed to dedup %s and %s - failed to create hard link from %s to %s" % (v1, v2, v2_link, v1))
             return 0
~~~
